name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello, world!
        run: echo "Hello, world!"
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2
          
      - name: Instalação do Mocha e dos pacotes para teste
        run: 
          cd src;
          npm install -g mocha;
          npm install
          
      - name: Execução do teste
        run: mocha src/test/convert.js
        
      - name: Docker HUB
        uses: docker/login-action@v2.2.0
        with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_PASSWORDS}}
        
      - name: Construção da imagem docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            vcosmusjoao/aula-conversao-temperatura:v1
            vcosmusjoao/aula-conversao-temperatura:latest
            
            
            
           
